### ISSUE TITLE
P&Q Bulletproofs 

### ISSUE THREAD

**Issue by ChristopherA** [ZcashFoundation/GrantProposals-2018Q2#16]
Is there any interest by the foundation in supporting bulletproofs using mirror curve to secp256k1 we are calling secq256kq? 

https://twitter.com/christophera/status/988856246349508609

**Comment by tromer** [comment]
The Foundation definitely has interest in supporting research and implementation of new cryptographic techniques for implementing privacy-preserving financial transactions.

I'm not sure what specifically you're proposing, since the Twitter link (at least as presented to me) shows nothing of substance.

The proposal should spell out the new approach, how this is applicable to the privacy-preserving public blobkchain setting, and what are the challenges (as well as the other general topics described in the Call for Proposals).

**Comment by zookozcash** [comment]
I think it might be the wrong link in the original post. I've seen different posts by Christopher A to Twitter about secq256kq.

**Comment by ChristopherA** [comment]
There are some more details from @maaku on secq at https://github.com/BlockchainCommons/secp256k1/issues/1

I’m out of town now (testifying on new Wyoming Blockchain laws) but plan to answer more questions next week.

**Comment by tromer** [comment]
The grant review committee needs further information, as discussed above, in order to evaluate your proposal.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 4 committee members .

The committee's opinion is that *your pre-proposal is not a leading candidate for funding in this round*, and the committee therefore does not invite you to submit a full proposal.
This decision is advisory, and you can still choose to submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). Note that if the full proposal is substantially the same as discussion so far reflects, then it's unlikely to be chosen for funding; and if it isn't, then we encourage you to post a draft (or at least answer any open questions) as early as possible, to allow for community feedback. Regardless of your choice, we thank you for participation thus far.
