### ISSUE TITLE
Zcash Education Outreach Part 2

### ISSUE THREAD

**Issue by techoluwoye** [ZcashFoundation/GrantProposals-2018Q2#30]
Zcash Proposal 2018 Q2
 

Over the last 6 months, the Coincentrix Team along with its partners have embarked on an exciting path of conducting grassroot Zcash and cryptocurrency evangelism across multiple Universities campuses in the United States. We are grateful for the opportunity granted to us by the Zcash Foundation to realize our 2017 Q 4 submission. Over the course of conducting outreach programs across these Universities, we discovered knowledge sharing is extremely vital to growing the utility and acceptance of cryptocurrency in today's world. 
Despite the presence of online educational content in the form of videos, articles, forums and social media; there is still a need for face to face interaction with cryptocurrency and blockchain enthusiast in an intimate environment. We were impressed by the curiosity of college students, faculty members, professionals and locals who were eager to learn about cryptocurrency, blockchain and most importantly Zcash in our outreach sessions.   
To highlight our accomplishment thus far, we have conducted outreach programs in four pilot universities including Howard University, Alabama A&M, Tennessee State University and  University of Alabama Birmingham. We also conducted educational sessions for organizations and businesses including, The Siamese Dreams, The National Society of Black Engineers, Alabama power, The Bessemer Public Library, Howard University’s African Business Club, Howard University Blockchain Labs, Alabama A&M Dean Speaker Series, Rooted shoes Store and the Pluckerz Restaurant. 
Throughout our initiative we partnered with Tyler Frost of Coinosophy, Matthew Rizzio and Sean Markert of BitBros to educate the audience on the fundamentals of cryptocurrency, blockchain technology, mining and Zcash. Overall, we had an attendance of over three hundred participants and we created the following key impacts:
Shared over a hundred Zcash T Shirts and collecting Pre & Post surveys to understand the impact of our outreach efforts.
Motivated Pluckerz Restaurant to enlist Zcash as a form of payment for it’s clients.  
Established relations with faculty members and residents in attendance for future outreach collaborations. 
Featured as a spotlight on WAFF 48, a local news station through Alabama A&M University’s public relations department while presenting at the Alabama A&M Dean Speaker Series.
Encouraged faculty members to integrate Zcash and blockchain technology into student projects as well as course materials within the various College of Engineering.
Met with David Bailey, the CEO of BTC Media who provided us with their magazines to distribute to our audience. 
Zcash Proposal:
Conduct Zcash outreach programs at additional universities with focus on more data collection and analysis to streamlined Zcash education and adoption. 
Interact with more businesses to promote Zcash as a form of payment. 
Leverage university relations to introduce cryptocurrency fundamentals and Zcash into existing curriculums within the school of Engineering.   
Motivation and overview:
As a result of completing workshops primarily in the South and Northeast regions, more interest within these and other regions such as the West Coast and NorthWest are increasing. 
We believe the long term value of the ZEC will depend on its users base over time. With the incline of Zcash network traffic mainly as a result of investment mediums; we want to take this opportunity to understand how we can include more businesses to accept Zcash as a payment option for their clients. 

 
![zcash transactions](https://user-images.githubusercontent.com/31833768/40215491-c8682fd2-5a2e-11e8-8eee-364d33cb3a47.png)

Technical approach:
Goals for this project will be achieved by:
(1) Leveraging existing relationships at educational institutions based on prior workshops provided to students and community members that addressed Bitcoin fundamentals.
(2) Conduct pre- and post-test surveys to examine the level of Zcash literacy before and after workshops.
(3) Develop programs encompassing of free Zcash educative courses and workshops, a with the main objective of tackling challenges identified from the survey data.
(4) Conduct pilot program at selected university
(5) Optimizing program per result of the pilot program

Team background and qualifications:
Oyedeji Oluwoye – Project Lead
Founder & CEO of Coincentrix Capital
Advisor to the Lamden Project
Coinosopher
Senior Specialist-Network Planning Engineer at AT&T Mobility
Master of Science Degree in Computer Science from Alabama A&M University
Master's Thesis: “Digital Cryptocurrencies: The Design and Network Analysis of the Bitcoin Infrastructure.”
Bachelors of Science Degree in Computer Science from Alabama A&M University
Certification
Bitcoin Certified Professional - CryptoCurrency Certification Consortium
Cisco CCNA, CCDA and Cisco CCNA Wireless Certified.
Comptia Network+

Pascal IV Ntsama – Material & Strategy Development
Founder & COO of Coincentrix Capital
RAN Design Engineer at AT&T Mobility
Bachelors of Science Degree in Electrical Engineering from Georgia Institute of Technology
Certification
Bitcoin Certified Professional - CryptoCurrency Certification Consortium
Other
Founder of Cameroonian Youth Empowerment (CYE) non-profit organization

Anthony Robinson - Marketing Coordinator
Regional Marketing Supervisor NW at The McDonalds Corporation
Bachelors of Arts Degree from Tennessee State University
Other
Project Coordination Glenn Anthony Homeless Project
Creator of Gold Plated Event Planning Group

Dr. Xiang Zhao - Project Advisor 
Alabama A&M University Faculty Liaison
Professor in the Department of Programing and Computer Science
Head of Alabama A&M University Computer Science Club

Evaluation plan
Grant Review Committee and/or other community members will be able to evaluate project success based on recorded visuals of the events created and social media updates through such platforms like Medium, Linkedin, Twitter and Zcash forum.

Security considerations
Implications of this project to the privacy, integrity, availability and decentralization of Zcash will be affected in a positive view with availability being a key focus. Community awareness will increase to the masses that have not been exposed to Blockchain technology and they will now see Zcash as the first option when thinking of the space. Education is a fundamental, knowledge of the Zcash project will in a capacity increase security measures taken by users to insure basic attacks on their wallets will be prevented. Pre- and post-test surveys will be anonymous and participants will not be asked to provide any identifying or personal information.

Budget and Justification
We project a budget of $10,000 - $15,000 USD for the workshops with increase demand in travel and resources . Details of the budget justification will be provided in final submission as we are evaluating the original costs from the pilot program and will have the accurate number once the deadline approaches.  

Email address(es) for direct contact

Email: o.oluwoye@coincentrix.io 
          info@coincentrix.io

**Comment by tromer** [comment]
For context, here are the proposal and (superb!) progress updates of this team's 2017Q4 grant award: https://github.com/ZcashFoundation/GrantProposals-2017Q4/issues/10

**Comment by alc-nmff** [comment]
Thank you for a very well structured proposal. I might have missed this, but what will be the timeframe for a project? 
Oh and results of those surveys are real treasures for an in-depth study!

**Comment by tromer** [comment]
What audience will you reach out to (in terms of institutions, geography or demographics)

To what extend does this extend beyond the audience covered in Part 1 of this project?

Are there products that can shared and reused by others?

**Comment by pascalEiv** [comment]
Hello @alc-nmff, the timeframe for the entire project will be roughly 4 to 6 months. However, this depends on how many institutions we can cover as per the amount awarded. In an average, we spend a month planning for all events both, academic and non-academic, and 3 months to execute about 2 events each month. 

The survey results will be shared in our 6 months report. We believe this data is vital to understand most importantly the general public's knowledge of Zcash. It is also important to consider that this exercise should be of a progressive manner, more data is needed to understand what factors will attract users (in this case, college students, and small business owners) to gravitate towards utilizing Zcash beyond an investment tool.

**Comment by pascalEiv** [comment]
Hello @tromer 

We will focus on two samples during one event, academia and small businesses located around the respective universities where the Zcash outreach event will occur. We are assigning more priority to academia because we believe they align with our future vision for students as well as faculty members implementing Zcash and its protocol zkSNARKs over typical academia functions such as, projects, research and curriculums. In addition we envision opportunities for students to develop solutions which eventually we be of use to their immediate environment (Small to medium size businesses around campus) .   On this round of our outreach programs, we will focus on providing the relevant content for our samples to nurture Zcash adoption. We will not be focusing on the audience covered in Part 1 of the project unless if we have identified opportunities which will further our studies. As far as the geography and demographics, we will focus on institutions in the Southeast, West and Northeast of the United States. 

I am not clear on your third questions but I assume you are asking, will our project generate some sort of value which could be shared and reused by others in the community ?. Yes, the main objective of our project is to streamline Zcash education and adoption. The value which will be sharable or reused are 

*Key factors to educating the general public about Zcash
*Key factors to promoting Zcash adoption into academia functions (Courses, Projects and Research). 
*Key Factors of promoting Zcash as a form of payment.

 Please let me know if i need to explain further.

**Comment by tromer** [comment]
About "products that can be shared", I mean material related to the events and activities. For example: presentation slides, demo software, lesson plans, survey forms and analysis spreadsheets?

**Comment by pascalEiv** [comment]
@tromer got it, we have presentation slides, a survey form and we are working on the analysis spreadsheet. We can share them all fairly soon.

**Comment by tromer** [comment]
The Zcash Foundation Grant Review committee has reviewed your pre-proposal, including the above discussion, to evaluate its potential and competitiveness relative to other proposals. Every pre-proposal was evaluated by at least 3 (and typically more than 4) committee members .

The committee's opinion is that *your pre-proposal is a promising candidate funding in this round*, and the committee therefore *invites you to submit a full proposal*.
Please submit a full proposal by June 15th, following the detailed structure described in the [Call for Proposals](https://github.com/ZcashFoundation/GrantProposals-2018Q2). We encourage you to submit a draft as early as possible, to  allow for community feedback.

**Comment by pascalEiv** [comment]
Hello Team, attached below is our official proposal. Thanks @techoluwoye  @tromer @alc-nmff for the feedback and comments!. Regards 
[Zcash Outreach Proposal ll.pdf](https://github.com/ZcashFoundation/GrantProposals-2018Q2/files/2107862/Zcash.Outreach.Proposal.ll.pdf)

**Comment by pascalEiv** [comment]
Hello Team, @tromer @alc-nmff @techoluwoye thank you for your comments and feedbacks. Attached is the final submission for the Zcash Outreach PART ll proposal.

Regards
[Zcash Outreach Proposal ll.pdf](https://github.com/ZcashFoundation/GrantProposals-2018Q2/files/2107868/Zcash.Outreach.Proposal.ll.pdf)

**Comment by sonyamann** [comment]
We regret to inform you that your submission was not selected by the Grant Review Committee, and hence the Zcash Foundation will not be funding this proposal. Thank you very much for your thoughtful contribution!

Please consider [subscribing to the Zcash Foundation newsletter](https://buttondown.email/zcashfoundation) so that you will be notified of future funding opportunities.

@tromer, can you supply the Grant Review Committee's comments for the Coincentrix team's reference?

**Comment by pascalEiv** [comment]
Thank you for the updates @sonyamann. When possible, please share the details from the Grant Review Commitee for references. We are subscribed to the newsletter and we will be in the look out for future opportunities. 

Regards.

**Comment by tromer** [comment]
The grant review committee's consensus comments are as follows:

This proposal would fund grassroots education, which is welcome and important. The team executed very well on their previous (2017 Q4) grant. However, the committee is concerned that this effort would be limited in impact due to the small audience that would be reached, and moreover that this audience overlaps with that of the previous grant to this team.

Regarding the workshop plans, there is inadequate planning and clarity about the intended nature and size audience, the length of the workshop, and most importantly the content.

The committee thus does not recommend funding this proposal. However, it encourages the Foundation to keep funding grass root efforts in general, balanced against resources and outreach to fresh audiences.

**Comment by pascalEiv** [comment]
Thank you @tromer
